title: Blog Cloudmetrix
description: Data Architect | Database | Cloud | AI

remote_theme: "mmistakes/minimal-mistakes@4.28.0"

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag

author:
  name: Giada Salvatori
  bio: Data Architect | Database | Cloud | AI
  location: Italy
