title: ""
site_title: ""
title_separator: ""

logo: "/assets/images/cloudmetrix.png"

remote_theme: "mmistakes/minimal-mistakes@4.28.0"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

author:
  name: Giada Salvatori

locale: it-IT

minimal_mistakes_skin: "default"
search: true

permalink: /:categories/:title/

include:
  - _pages

sass:
  style: compressed
